---
- name: build switch
  hosts: leaf
  connection: local
  gather_facts: no

  tasks:

   

    - name: Configure interfaces
      nxos_interface:
        description: "{{ item.description }}"
        interface: "{{ item.interface }}"
        mode: layer3
        state: present
      with_items: "{{ interfaces }}"

    - name: Configure interfaces Layer3
      nxos_l3_interface:
        ipv4: "{{ item.ipv4 }}"
        name: "{{ item.interface }}"
      with_items: "{{ interfaces }}"

    - name: CHANGE INTERFACE MTU TO 9216
      nxos_interface:
        mtu: 9216
        interface: "{{ item.interface }}"
        state: present
      with_items: "{{ l3_interfaces }}"


    - name: CONFIGURE L2 INTERFACES/SWITCHPORTS
      nxos_interface:
        interface: "{{ item.interface }}"
        mode: layer2
        admin_state: up
      with_items: "{{ l2_interfaces }}"

    - name: CONFIGURE L2 INTERFACES/SWITCHPORTS (TRUNKS)
      nxos_switchport:
        interface: "{{ item.interface }}"
        mode: trunk
        trunk_vlans: 10-15,20-25,30-35,40-45,50-55
      with_items: "{{ l2_interfaces }}"

