---
- name: build switch
  hosts: spine
  connection: local
  gather_facts: no

  tasks:


    - name: enable nxos_features
      nxos_feature:
        feature: "{{ item.feature }}"
        state: enabled
      with_items: "{{ nxos_feature }}"

    - name: ENABLE NV OVERLAY EVPN
      nxos_evpn_global:
        nv_overlay_evpn: true
 
    - name: Configure interfaces
      nxos_interface:
        description: "{{ item.description }}"
        interface: "{{ item.interface }}"
        mode: layer3
        state: present
      with_items: "{{ interfaces }}"

    - name: Configure interfaces Layer3
      nxos_l3_interface:
        ipv4: "{{ item.ipv4 }}"
        name: "{{ item.interface }}"
      with_items: "{{ interfaces }}"

    - name: Enable ospf process
      nxos_ospf:
        ospf: 1
        state: present

    - name: Configure ospf interfaces
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: 1
        area: 0
        cost: default
        state: present
      with_items: "{{ ospf_interfaces }}"

