---
- name: build switch
  hosts: spine
  connection: local
  gather_facts: no

  tasks:


    - name: enable nxos_features
      nxos_feature:
        feature: "{{ item.feature }}"
        state: enabled
      with_items: "{{ nxos_feature }}"

    - name: ENABLE NV OVERLAY EVPN
      nxos_evpn_global:
        nv_overlay_evpn: true
 
    - name: Configure interfaces
      nxos_interface:
        description: "{{ item.description }}"
        interface: "{{ item.interface }}"
        mode: layer3
        state: present
      with_items: "{{ interfaces }}"

    - name: Configure interfaces Layer3
      nxos_l3_interface:
        ipv4: "{{ item.ipv4 }}"
        name: "{{ item.interface }}"
      with_items: "{{ interfaces }}"

    - name: CHANGE INTERFACE MTU TO 9216
      nxos_interface:
        mtu: 9216
        interface: "{{ item.interface }}"
        state: present
      with_items: "{{ l3_interfaces }}"

    - name: Enable ospf process
      nxos_ospf:
        ospf: 1
        state: present

    - name: Configure ospf interfaces
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: 1
        area: 0
        cost: default
        state: present
      with_items: "{{ ospf_interfaces }}"

    - name: CONFIGURE OSPF INTERFACES NETWORK P2P
      nxos_config:
        lines: ip ospf network point-to-point
        parents:
          - 'interface {{ item.interface }}'
      with_items: "{{ l3_interfaces }}"

    - name: CONFIGURE PIM ANYCAST RP
      nxos_config:
        lines:
          - "ip pim anycast-rp {{ rp_address }} {{ s1_loopback }}"
          - "ip pim anycast-rp {{ rp_address }} {{ s2_loopback }}"

    - name: CONFIGURE PIM RP
      nxos_pim_rp_address:
        rp_address: "{{ rp_address }}"

    - name: CONFIGURE PIM INTERFACES
      nxos_pim_interface:
        interface: "{{ item.interface }}"
        sparse: true
      with_items: "{{ pim_interfaces }}"


    - name: CONFIGURE BGP ASN AND ROUTER ID
      nxos_bgp:
        asn: "{{ asn }}"
        router_id: "{{ router_id }}"
        state: present

    - name: CONFIGURE BGP NEIGHBORS
      nxos_bgp_neighbor:
        asn: "{{ asn }}"
        neighbor: "{{ item.neighbor }}"
        remote_as: "{{ item.remote_as }}"
        update_source: "{{ item.update_source }}"
      with_items: "{{ bgp_neighbors }}"

    - name: CONFIGURE L2VPN EVPN ADDRESS FAMILY FOR BGP NEIGHBORS
      nxos_bgp_neighbor_af:
        asn: "{{ asn }}"
        neighbor: "{{ item.neighbor }}"
        afi: l2vpn
        safi: evpn
        send_community: both
        route_reflector_client: "true"
      with_items: "{{ bgp_neighbors }}"


