---
- name: build switch
  hosts: all
  connection: local
  gather_facts: no

  tasks:

    - debug: var=item
      with_items: "{{ interfaces }}"

    - name: Configure interfaces
      nxos_interface:
        interface: "{{ item.interface }}"
        mode: layer3
        state: present
      with_items: "{{ interfaces }}"

    - name: Configure interfaces
      nxos_l3_interface:
        ipv4: "{{ item.ipv4 }}"
        name: "{{ item.interface }}"
      with_items: "{{ interfaces }}"
    
    - name: Ensure ospf is enabled
      nxos_feature:
        feature: ospf
        state: enabled

    - name: Enable ospf process
      nxos_ospf:
        ospf: 1
        state: present

    - name: Configure ospf interfaces
      nxos_interface_ospf:
        interface: "{{ item.interface }}"
        ospf: 1
        area: 0
        cost: default
        state: present
      with_items: "{{ ospf_interfaces }}"
