


---

- name: remove n9k1
  hosts: n9k1 
  connection: local
  gather_facts: no 

  tasks:
    
    - name:  remove LOOP 0
      nxos_interface: interface=loopback0 state=absent host={{ inventory_hostname }}
      register: data

    - name: Ensure ospf is disabled
      nxos_feature:
       feature: ospf
       state: disabled
    
    - nxos_interface_ospf:
        interface: loopback0
        ospf: 1
        area: 0
        cost: default
        state: absent  

 
    - name: Ensure bgp is disabled
      nxos_feature:
       feature: bgp
       state: disabled

- name: remove n9k2
  hosts: n9k2
  connection: local
  gather_facts: no

  tasks:

    - name: remove LOOP 0
      nxos_interface: interface=loopback0 state=absent host={{ inventory_hostname }}
      register: data

    - name: Ensure ospf is disabled
      nxos_feature:
       feature: ospf
       state: disabled

    - name: Ensure bgp is disabled
      nxos_feature:
       feature: bgp
       state: disabled

- name: remove n9k3
  hosts: n9k3
  connection: local
  gather_facts: no

  tasks:

    - name: remove LOOP 0
      nxos_interface: interface=loopback0 state=absent host={{ inventory_hostname }}
      register: data

    - name: Ensure ospf is disabled
      nxos_feature:
       feature: ospf
       state: disabled

    - name: Ensure bgp is disabled
      nxos_feature:
       feature: bgp
       state: disabled

- name: remove n9k4
  hosts: n9k4
  connection: local
  gather_facts: no

  tasks:

    - name: remove LOOP 0
      nxos_interface: interface=loopback0 state=absent host={{ inventory_hostname }}
      register: data

    - name: Ensure ospf is disabled
      nxos_feature:
       feature: ospf
       state: disabled

    - name: Ensure bgp is disabled
      nxos_feature:
       feature: bgp
       state: disabled

- name: remove n9k5
  hosts: n9k5
  connection: local
  gather_facts: no

  tasks:

    - name: remove LOOP 0
      nxos_interface: interface=loopback0 state=absent host={{ inventory_hostname }}
      register: data

    - name: Ensure ospf is disabled
      nxos_feature:
       feature: ospf
       state: disabled

    - name: Ensure bgp is disabled
      nxos_feature:
       feature: bgp
       state: disabled
